(vim.lsp.enable :biome)
(vim.lsp.enable :codebook)
(vim.lsp.enable :clojure_lsp)
(vim.lsp.enable :fennel_ls)
(vim.lsp.enable :harper_ls)
(vim.lsp.enable :nixd)
(vim.lsp.enable :rust_analyzer)
(vim.lsp.enable :tsgo)
